# Generated by Django 4.2 on 2023-05-02 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stations',
            fields=[
                ('station', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('line', models.CharField(max_length=40)),
            ],
        ),
    ]
