# Generated by Django 4.2 on 2023-05-03 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stations',
            name='slug',
            field=models.SlugField(default='7호선', max_length=60),
        ),
    ]
